#pragma once
#include "sdkconfig.h"
#include "esp_err.h"

/* Physical GPIOs only. Array order defines logical bit significance. */
#define C5VRX_IQ_GPIOS { CONFIG_C5VRX_IQ_D0_GPIO, CONFIG_C5VRX_IQ_D1_GPIO, CONFIG_C5VRX_IQ_D2_GPIO, CONFIG_C5VRX_IQ_D3_GPIO, CONFIG_C5VRX_IQ_D4_GPIO, CONFIG_C5VRX_IQ_D5_GPIO, CONFIG_C5VRX_IQ_D6_GPIO, CONFIG_C5VRX_IQ_D7_GPIO }
#if CONFIG_C5VRX_DAC_BITS == 8
#define C5VRX_DAC_GPIOS { CONFIG_C5VRX_DAC_D0_GPIO, CONFIG_C5VRX_DAC_D1_GPIO, CONFIG_C5VRX_DAC_D2_GPIO, CONFIG_C5VRX_DAC_D3_GPIO, CONFIG_C5VRX_DAC_D4_GPIO, CONFIG_C5VRX_DAC_D5_GPIO, CONFIG_C5VRX_DAC_D6_GPIO, CONFIG_C5VRX_DAC_D7_GPIO }
#else
#define C5VRX_DAC_GPIOS { CONFIG_C5VRX_DAC_D0_GPIO, CONFIG_C5VRX_DAC_D1_GPIO, CONFIG_C5VRX_DAC_D2_GPIO, CONFIG_C5VRX_DAC_D3_GPIO, CONFIG_C5VRX_DAC_D4_GPIO, CONFIG_C5VRX_DAC_D5_GPIO, -1, -1 }
#endif

#if CONFIG_C5VRX_DAC_BITS == 8 && (!CONFIG_C5VRX_PHASE8_HR_LIVE_TEST || defined(C5VRX4_EXPERIMENT))
#error "8-bit DAC requires the root Phase8 live pipeline"
#endif

/* Call before RF/probes claim any GPIOs. */
esp_err_t board_config_validate(void);
