#!/usr/bin/env python3
"""Emit fixed-work C5 BitScrambler M2M throughput probes (K=1..8).

Each pair consumes and emits 16 bits. The other K-1 bundles perform no I/O.
The output is zero so no data-dependent lookup or pipeline priming can skew
the instruction-rate measurement. These programs are not FM demodulators.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "main"


def program(k):
    assert 1 <= k <= 8
    lines = ["# Generated by tools/gen_bs_speedlab.py; exactly K bundles / 16-bit pair.",
             "cfg prefetch true", "cfg eof_on downstream",
             "cfg trailing_bytes 10", "cfg lut_width_bits 16", ""]
    for i in range(k):
        lines += [f"step_{i}:"]
        if i == k - 1:
            lines += ["    set 0..15 L,", "    read 16,", "    write 16,",
                      "    jmp step_0"]
        else:
            lines += ["    set 31 L"]
        lines += [""]
    return "\n".join(lines)


def main():
    for k in range(1, 9):
        (ROOT / f"bs_speedlab_k{k}.bsasm").write_text(program(k), encoding="ascii")


if __name__ == "__main__":
    main()
