#!/usr/bin/env python3
"""Bounded video transfer with a 32-state Phase8-derived codebook.

This is deliberately NOT full 8-bit endpoint state: two LUT lookups per pair
fit only 32x32 endpoint combinations. Keep PHASE8_FULL for that comparison.
All Q4 bits participate, with Phase8 cell-centre angles used to design the
codebook. No CPU processing, gain writes, or extra realtime bundles.
"""
from pathlib import Path
import math
from gen_phase8_hr import phase8

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "main/fm_phase8_video.bsasm"
HEADER = ROOT / "main/phase8_video_lut.h"

def wrap(d):
    return (d + 128) % 256 - 128

def codebook():
    # Deterministic annulus corpus; these are design weights, not RF evidence.
    weight = [0] * 256
    for radius in (1.6, 2.5, 4.0, 5.5):
        for k in range(4096):
            a = 2 * math.pi * (k + 0.5) / 4096
            i, q = math.floor(radius * math.cos(a)), math.floor(radius * math.sin(a))
            weight[((i & 15) << 4) | (q & 15)] += 1
    centres = [8.0 * k for k in range(32)]
    for _ in range(64):
        groups = [[] for _ in centres]
        for raw, w in enumerate(weight):
            if w:
                p = phase8(raw)
                j = min(range(32), key=lambda j: abs(wrap(p - centres[j])))
                groups[j].append((p, w))
        updated = centres.copy()
        for j, group in enumerate(groups):
            if group:
                updated[j] = (centres[j] + sum(wrap(p - centres[j]) * w for p, w in group)
                              / sum(w for _, w in group)) % 256
        if max(abs(wrap(a - b)) for a, b in zip(updated, centres)) < 1e-9:
            break
        centres = updated
    reps = [round(c) & 255 for c in centres]
    states = [min(range(32), key=lambda j: abs(wrap(phase8(raw) - reps[j])))
              for raw in range(256)]
    return states, reps

def dac(delta):
    # P20, 3/4 code per Phase8 bin, positive FM polarity. Saturate before
    # conversion, NEVER modulo-wrap the amplified result. Suppress the far
    # discriminator tail gradually: this is a video prior, not a claim that
    # every >135-degree step is invalid. Full-range mode remains available.
    value = max(0, min(63, round(20 + 0.75 * delta)))
    tail = abs(delta)
    if tail >= 112:
        return 20
    if tail > 96:
        value = round(20 + (value - 20) * (112 - tail) / 16)
    return value

def build():
    states, reps = codebook()
    codes = [dac(wrap(reps[c] - reps[p])) for p in range(32) for c in range(32)]
    words = [states[a & 255] | (codes[a] << 8) for a in range(1024)]
    asm = """# Phase8 VIDEO32: Phase8-derived 32-state codebook, bounded P20/G3 transfer.
# 40 MS/s Q4 input, 20 MS/s unique DAC [D,D], exactly two bundles.
# State persists across every DMA boundary. No CPU video DSP.
cfg prefetch true
cfg eof_on downstream
cfg trailing_bytes 0
cfg lut_width_bits 16
lut """ + " ".join(map(str, words)) + "\n\n"
    # Unroll for implicit PC wrapping; no arithmetic/branch timing ambiguity.
    for k in range(4):
        asm += f"""controller_{k}:
    set 26..30 L0..L4,
    set 16..20 L0..L4,
    set 21..25 O26..O30

worker_{k}:
    set 0..5 L8..L13,
    set 8..13 L8..L13,
    set 16..23 8..15,
    set 26..30 O26..O30,
    read 16,
    write 16

"""
    header = '#pragma once\n/* Generated by tools/gen_phase8_video.py. */\n'
    for name, data in (("state", states), ("phase", reps), ("dac", codes)):
        header += f'static const unsigned char c5vrx_phase8_video_{name}[{len(data)}] = {{\n'
        for start in range(0, len(data), 16):
            header += '    ' + ', '.join(map(str, data[start:start + 16])) + ',\n'
        header += '};\n'
    return asm, header, states, reps, codes

if __name__ == '__main__':
    asm, header, *_ = build()
    TARGET.write_text(asm)
    HEADER.write_text(header)
    print('Generated Phase8 VIDEO32 (bounded transfer; 5-bit endpoint state)')
